server:
    port: ${PORT:8080}

spring:
    application:
        name: service-catalogue
    data:
        mongodb:
            uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:toor}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/solutiondb?authSource=admin