server:
    port: ${PORT:8082}

spring:
    application:
        name: service-warehouse
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: 5672
        username: guest
        password: guest
    data:
        mongodb:
            uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:toor}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/solutiondb?authSource=admin